services:
  django-project-structure:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
      # dockerfile: ./deployments/Dockerfile_dev
      args:
        - ENVIRONMENT=develpment
    image: django-project-structure
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    networks:
      - django-project-structure-network
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"

networks:
  django-project-structure-network:
