version: "3.9"

services:
  django_project_structure:
    build:
      context: ../
      dockerfile: ./deployments/Dockerfile
      # dockerfile: ./deployments/Dockerfile_dev
      args:
        - ENVIRONMENT=develpment
    image: django_project_structure
    ports:
      - "8000:8000"
    volumes:
      - ../:/app
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
